### ISSUE TITLE
trips out in Safari Version 9.0.1 (11601.2.7.2)

### ISSUE THREAD

**Issue by odeke-em** [y-js/shared-filesystem#2]
When I visit a shared link, I get
<img width="1265" alt="screen shot 2016-05-11 at 1 53 52 am" src="https://cloud.githubusercontent.com/assets/4898263/15175493/77d2564a-171b-11e6-9fd9-70eee2789394.png">

<img width="1271" alt="screen shot 2016-05-11 at 1 55 49 am" src="https://cloud.githubusercontent.com/assets/4898263/15175502/83bf6b0a-171b-11e6-9f27-5f96858b0dce.png">
#### Safari Version

<img width="286" alt="screen shot 2016-05-11 at 1 56 21 am" src="https://cloud.githubusercontent.com/assets/4898263/15175535/a4aba202-171b-11e6-8cb1-0e3aca28f213.png">

**Comment by dmonad** [comment]
That's some quality issue report. It is related to #1. I am going to fix it later today

**Comment by odeke-em** [comment]
Dope. Thank you for fixing this!
